package com.univeris.cxp.questionnaire;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.google.common.collect.ArrayListMultimap;
import com.google.common.collect.LinkedHashMultimap;
import com.google.common.collect.Multimap;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.Filters;

/**
 * This file is an Entity Class generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 */

@Entity
@Table(name = "answeredquestionnaire")
@Filters({@Filter(name = "archiveFilterDef"), @Filter(name = "tenantFilterDef")})
public class AnsweredQuestionnaire extends AnsweredQuestionnaireBase
		implements
			java.io.Serializable {
	private static final long serialVersionUID = -1880888387L;
	
	@Transient
	public List<AnsweredQuestionSection>  getAnsweredQuestionSections(){
		
		
		com.google.common.collect.Multimap<Section, AnsweredQuestion> mapAnsweredQuestions = ArrayListMultimap.create(); //<Section, AnsweredQuestion>
			
		List<AnsweredQuestionSection> answeredQuestionSections = new ArrayList<AnsweredQuestionSection>();
		
		for(AnsweredQuestion aq: answeredQuestions){
			mapAnsweredQuestions.put(aq.getQuestion().getSection(), aq);
		}
		
		for (Section section : mapAnsweredQuestions.keySet()){
			answeredQuestionSections.add(new AnsweredQuestionSection(section, (List<AnsweredQuestion>) mapAnsweredQuestions.get(section) ));
		}
		
		return answeredQuestionSections;
		
	}
	
}
